---
- name: Download Go
  get_url:
    checksum: "{{ go_sha256sum }}"
    url: "{{ go_base_url }}{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz"
    dest: "/tmp/go{{ go_version }}.{{ go_os }}.{{ go_arch }}.tar.gz"
  
- name: Extract Go
  become: yes
  unarchive:
    remote_src: yes
    src: "/tmp/go{{ go_version }}.{{ go_os }}.{{ go_arch }}.tar.gz"
    dest: /usr/local/

- name: Add Go to PATH system-wide
  become: yes
  lineinfile:
    path: /etc/profile
    line: export PATH=$PATH:/usr/local/go/bin
